const danceData = {
  kids: {
    label: 'Kids 4–12',
    styles: {
      bollywood: { icon:'⭐', name:'Bollywood', chips:['Most loved for 4–12','Playful and energetic','Beginner friendly'], quote:'Kids love Bollywood because it feels colorful, playful, and easy to copy from songs.', text:'Bollywood is popular for kids because it mixes joyful music, facial expressions, drama, and high-energy steps. For kids, the learning focus is fun, coordination, confidence, rhythm memory and safe movement.', origin:'Indian cinema and stage performance', why:'Great for confidence, memory, stamina and joyful performance.', skills:['Expressions','Hand gestures','Footwork','Stage presence'], lessons:['Step-touch for 8 counts','Shoulder bounce + clap','Simple hand wave pattern','Final pose with smile'] },
      hiphop: { icon:'🧢', name:'Hip Hop', chips:['High energy','Cool moves','Confidence'], quote:'Kids enjoy Hip Hop because it feels cool, bouncy, and full of personality.', text:'Hip Hop helps kids develop rhythm, balance, body control and confidence. The best approach is simple grooves, bounce, isolation and freestyle games.', origin:'Street dance culture, USA', why:'Great for rhythm, confidence and body coordination.', skills:['Bounce','Groove','Isolation','Freestyle'], lessons:['Bounce on beat','Two-step groove','Arm isolation','Freeze pose'] },
      freestyle: { icon:'⚡', name:'Freestyle', chips:['Creative','No pressure','Fun'], quote:'Freestyle is perfect for kids because it lets them move without fear of mistakes.', text:'Freestyle teaches children to listen to music and create movement naturally. It builds imagination, self-expression and confidence.', origin:'Open creative dance', why:'Great for creativity and emotional expression.', skills:['Imagination','Musicality','Confidence','Movement flow'], lessons:['Move to drum beats','Copy animal movement','Create 4-step combo','Perform with expression'] },
      bharatanatyam: { icon:'🏛️', name:'Bharatanatyam', chips:['Cultural','Discipline','Expression'], quote:'Kids learn patience, posture and storytelling through Bharatanatyam.', text:'Bharatanatyam introduces discipline, strong posture, hand gestures and expressive storytelling. For kids, lessons should be short, safe and playful.', origin:'Tamil Nadu, India', why:'Great for posture, focus and cultural learning.', skills:['Mudras','Posture','Rhythm','Expressions'], lessons:['Namaskaram basics','Simple mudras','Half-sitting posture','Expression practice'] },
      kathak: { icon:'💫', name:'Kathak', chips:['Spins','Rhythm','Storytelling'], quote:'Kathak gives kids rhythm, elegance and storytelling skills.', text:'Kathak is known for footwork, spins and graceful storytelling. Kids usually love the rhythmic claps, counting and chakkars.', origin:'North India', why:'Great for timing, grace and focus.', skills:['Tatkar','Chakkars','Mudras','Rhythm count'], lessons:['Clap counts','Basic tatkar','One slow spin','Story gesture'] },
      jazz: { icon:'🎷', name:'Jazz', chips:['Stage style','Energy','Performance'], quote:'Jazz helps kids perform with bright energy and strong stage confidence.', text:'Jazz combines sharp movements, kicks, turns and expressive stage performance. It is exciting and works well for energetic children.', origin:'African-American performance dance', why:'Great for stage presence and flexibility.', skills:['Kicks','Turns','Lines','Performance face'], lessons:['Jazz walk','Step-kick','Arm lines','Ending pose'] },
      contemporary: { icon:'🌙', name:'Contemporary', chips:['Expressive','Soft movement','Creative'], quote:'Contemporary helps kids express feelings through soft flowing movement.', text:'Contemporary dance focuses on flow, balance, emotions and storytelling through body movement. Kids can learn it with safe floor movements and simple shapes.', origin:'Modern concert dance', why:'Great for emotional expression and balance.', skills:['Flow','Balance','Shapes','Storytelling'], lessons:['Reach and fold','Slow turn','Floor shape','Emotion movement'] },
      salsa: { icon:'🌶️', name:'Salsa', chips:['Rhythm','Partner basics','Fun'], quote:'Salsa gives kids a playful way to understand rhythm and coordination.', text:'For kids, salsa should focus on basic timing, simple side steps and rhythm awareness rather than complex partner work.', origin:'Latin dance culture', why:'Great for rhythm and coordination.', skills:['Timing','Side steps','Claps','Coordination'], lessons:['Basic side step','Clap rhythm','Forward-back step','Partner mirror game'] },
      folk: { icon:'🥁', name:'Folk Dance', chips:['Cultural','Group dance','Celebration'], quote:'Folk dance helps kids feel culture, teamwork and celebration.', text:'Folk dance is wonderful for children because it is social, rhythmic and connected to festivals, stories and community.', origin:'Regional traditions worldwide', why:'Great for teamwork and cultural connection.', skills:['Group timing','Simple patterns','Energy','Tradition'], lessons:['Circle step','Clap pattern','Group formation','Festival rhythm'] },
      ballet: { icon:'🩰', name:'Ballet', chips:['Grace','Balance','Posture'], quote:'Ballet builds posture, balance and graceful control from an early age.', text:'Ballet teaches discipline, balance, flexibility and body alignment. For kids, it should remain gentle, playful and age-appropriate.', origin:'European court dance', why:'Great for balance, posture and discipline.', skills:['Posture','Balance','Pointing feet','Grace'], lessons:['First position','Gentle plié','Arm port de bras','Balance hold'] }
    }
  },
  teens: {
    label: 'Teens 13–18',
    styles: {
      hiphop: { icon:'🧢', name:'Hip Hop', chips:['Most popular','Style identity','Performance'], quote:'Teens love Hip Hop because it feels confident, modern and expressive.', text:'Hip Hop is one of the most popular teen dance styles because it connects with current music, social trends and self-expression. It helps teens build confidence, groove, stamina and stage attitude.', origin:'Street and club culture, USA', why:'Great for confidence, fitness and personal style.', skills:['Groove','Isolation','Freestyle','Stage attitude'], lessons:['Bounce variations','Body isolation combo','Freestyle 8 counts','Performance ending'] },
      bollywood: { icon:'⭐', name:'Bollywood', chips:['Expressive','Popular songs','Stage-ready'], quote:'Bollywood lets teens combine drama, expression and high-energy performance.', text:'Bollywood is perfect for teens who enjoy music, performance and expressive storytelling. It improves stamina, confidence and stage presence.', origin:'Indian cinema', why:'Great for performance confidence and expressive movement.', skills:['Expressions','Energy','Transitions','Musicality'], lessons:['Hook-step practice','Expression drill','Fast footwork combo','Group formation'] },
      freestyle: { icon:'⚡', name:'Freestyle', chips:['Personal style','Creative','Social'], quote:'Freestyle lets teens develop their own dance identity.', text:'Freestyle helps teens become comfortable with music and movement without copying everything. It builds confidence, creativity and improvisation.', origin:'Creative street and social dance', why:'Great for originality and confidence.', skills:['Improvisation','Musicality','Transitions','Confidence'], lessons:['Move to bass','Change levels','Freestyle circle','Signature move'] },
      contemporary: { icon:'🌙', name:'Contemporary', chips:['Emotional','Artistic','Flow'], quote:'Contemporary gives teens a powerful way to express emotion through movement.', text:'Contemporary is popular with teens who like expressive, artistic movement. It teaches flow, control, balance, floor work and storytelling.', origin:'Modern and postmodern dance', why:'Great for expression and body control.', skills:['Flow','Control','Floor work','Emotion'], lessons:['Reach and release','Fall and recover','Turn sequence','Emotion phrase'] },
      jazz: { icon:'🎷', name:'Jazz', chips:['Stage performance','Sharp lines','Energy'], quote:'Jazz gives teens clean lines, powerful energy and stage confidence.', text:'Jazz is excellent for teens interested in performances, musicals or stage routines. It builds flexibility, sharpness and projection.', origin:'African-American jazz culture and theatre', why:'Great for stage presence and flexibility.', skills:['Lines','Turns','Kicks','Projection'], lessons:['Jazz square','Kick sequence','Turn prep','Stage walk'] },
      ballet: { icon:'🩰', name:'Ballet', chips:['Foundation','Discipline','Control'], quote:'Ballet gives teens strong technique that improves almost every dance style.', text:'Ballet builds posture, strength, flexibility and discipline. Teens benefit from its technical foundation even if they later choose modern or stage styles.', origin:'European classical dance', why:'Great for technique and body alignment.', skills:['Alignment','Balance','Strength','Grace'], lessons:['Barre basics','Plié and tendu','Core control','Simple adagio'] },
      salsa: { icon:'🌶️', name:'Salsa', chips:['Social rhythm','Partner work','Confidence'], quote:'Salsa helps teens understand rhythm, timing and social dance etiquette.', text:'Salsa introduces rhythm, timing and partner coordination. It should be taught respectfully with focus on basic footwork and musicality.', origin:'Latin America and Caribbean influence', why:'Great for timing and social confidence.', skills:['Timing','Footwork','Partner awareness','Musicality'], lessons:['Basic step','Right turn','Cross-body rhythm','Partner timing'] },
      kathak: { icon:'💫', name:'Kathak', chips:['Rhythm mastery','Grace','Culture'], quote:'Kathak gives teens discipline, rhythm and graceful storytelling.', text:'Kathak is powerful for teens who enjoy culture and precision. It builds strong footwork, spins, rhythm counting and expressive storytelling.', origin:'North India', why:'Great for rhythm, patience and cultural connection.', skills:['Tatkar','Chakkars','Abhinaya','Laya'], lessons:['Tatkar speed control','Spin spotting','Hand gesture phrase','Rhythm cycle'] },
      bharatanatyam: { icon:'🏛️', name:'Bharatanatyam', chips:['Classical','Discipline','Expression'], quote:'Bharatanatyam gives teens strength, expression and cultural depth.', text:'Bharatanatyam builds stamina, posture, expression and discipline. Teens can understand deeper storytelling and cultural meaning.', origin:'Tamil Nadu, India', why:'Great for discipline, strength and expression.', skills:['Adavus','Mudras','Araimandi','Abhinaya'], lessons:['Adavu practice','Mudra meaning','Expression story','Posture strength'] },
      folk: { icon:'🥁', name:'Folk Dance', chips:['Group energy','Festive','Culture'], quote:'Folk dance gives teens energetic group performance and cultural pride.', text:'Folk dance is popular for events and celebrations. It builds stamina, group coordination and cultural connection.', origin:'Regional community traditions', why:'Great for teamwork and festival performance.', skills:['Group sync','Rhythm','Energy','Formation'], lessons:['Formation changes','Clap rhythm','Travel steps','Group finale'] }
    }
  },
  adults: {
    label: 'Adults 19+',
    styles: {
      salsa: { icon:'🌶️', name:'Salsa', chips:['Most social','Fitness','Stress relief'], quote:'Adults love Salsa because it feels social, musical and energizing.', text:'Salsa is one of the most popular adult dance styles because it improves rhythm, coordination, confidence and fitness while feeling social and enjoyable.', origin:'Latin American and Caribbean dance culture', why:'Great for fitness, rhythm and social confidence.', skills:['Timing','Partner awareness','Footwork','Musicality'], lessons:['Basic step','Side basic','Right turn','Simple shine'] },
      bollywood: { icon:'⭐', name:'Bollywood', chips:['Joyful fitness','Cultural','High energy'], quote:'Bollywood helps adults enjoy fitness through expressive music and celebration.', text:'Bollywood is ideal for adults who want energetic movement, cultural expression and fun cardio without the pressure of technical perfection.', origin:'Indian cinema and stage performance', why:'Great for stamina, mood and expression.', skills:['Energy','Expressions','Coordination','Cardio'], lessons:['Warm-up groove','Hook step','Expression phrase','Cardio combo'] },
      contemporary: { icon:'🌙', name:'Contemporary', chips:['Expressive','Mobility','Mind-body'], quote:'Contemporary helps adults release stress and reconnect with movement.', text:'Contemporary is excellent for adults who want expressive, mindful and flowing movement. It supports mobility, balance and emotional expression.', origin:'Modern concert dance', why:'Great for stress relief, mobility and expression.', skills:['Flow','Balance','Breath','Control'], lessons:['Breath-led movement','Reach and release','Slow turn','Short phrase'] },
      hiphop: { icon:'🧢', name:'Hip Hop', chips:['Cardio','Confidence','Groove'], quote:'Hip Hop gives adults a fun way to build confidence and fitness.', text:'Adult beginners can learn Hip Hop through grooves, bounce and simple combinations. It is strong cardio and helps reduce stiffness.', origin:'Street dance culture, USA', why:'Great for cardio, confidence and rhythm.', skills:['Bounce','Groove','Isolation','Stamina'], lessons:['Bounce basics','Two-step','Body roll intro','Groove combo'] },
      ballet: { icon:'🩰', name:'Ballet', chips:['Posture','Strength','Grace'], quote:'Ballet gives adults posture, strength and graceful body control.', text:'Adult ballet is excellent for alignment, core strength, flexibility and calm focus. It should be practiced gently and consistently.', origin:'European classical dance', why:'Great for posture, flexibility and discipline.', skills:['Alignment','Core','Balance','Grace'], lessons:['Barre posture','Plié','Tendu','Balance practice'] },
      kathak: { icon:'💫', name:'Kathak', chips:['Rhythm','Grace','Culture'], quote:'Kathak gives adults rhythm, elegance and cultural storytelling.', text:'Kathak is meaningful for adults who enjoy classical rhythm, spins, expressions and Indian cultural storytelling.', origin:'North India', why:'Great for rhythm, memory and graceful expression.', skills:['Tatkar','Chakkars','Mudras','Expression'], lessons:['Basic tatkar','Clap cycle','Slow chakkar','Story gesture'] },
      bharatanatyam: { icon:'🏛️', name:'Bharatanatyam', chips:['Strength','Tradition','Expression'], quote:'Bharatanatyam offers adults discipline, strength and cultural depth.', text:'Adult beginners can learn Bharatanatyam through posture, adavus, mudras and expressive storytelling at a safe pace.', origin:'Tamil Nadu, India', why:'Great for strength, focus and cultural learning.', skills:['Posture','Adavus','Mudras','Stamina'], lessons:['Namaskaram','Basic adavu','Mudra practice','Expression drill'] },
      jazz: { icon:'🎷', name:'Jazz', chips:['Energy','Stage style','Flexibility'], quote:'Jazz helps adults feel energetic, stylish and performance-ready.', text:'Jazz combines stage movement, rhythm and expressive confidence. Adult beginners can start with simple walks, kicks and arm lines.', origin:'Jazz music and theatre dance', why:'Great for energy and stage confidence.', skills:['Lines','Kicks','Turns','Projection'], lessons:['Jazz walk','Step kick','Arm lines','Pose finish'] },
      freestyle: { icon:'⚡', name:'Freestyle', chips:['Freedom','No rules','Confidence'], quote:'Freestyle is ideal for adults who want freedom without judgment.', text:'Freestyle lets adults move naturally with music. It is great for stress relief, body confidence and creativity.', origin:'Creative social dance', why:'Great for confidence and self-expression.', skills:['Musicality','Creativity','Flow','Confidence'], lessons:['Move to melody','Change levels','Repeat a motif','Create 8 counts'] },
      folk: { icon:'🥁', name:'Folk Dance', chips:['Community','Culture','Celebration'], quote:'Folk dance gives adults community, tradition and joyful group movement.', text:'Folk dance is excellent for adults because it is social, cultural and energetic. It works well for festivals, family events and community gatherings.', origin:'Regional traditions worldwide', why:'Great for community, stamina and cultural identity.', skills:['Group rhythm','Simple steps','Formation','Energy'], lessons:['Circle pattern','Clap step','Travel step','Group ending'] }
    }
  }
};

const styleMeta = [
 ['Bollywood','India','Expressions, footwork, hand movement and musical drama.','High energy storytelling'],
 ['Hip-Hop','USA','Bounce, groove, isolation, freestyle and stage attitude.','Groove and confidence'],
 ['Kathak','North India','Tatkar footwork, chakkars, mudras and graceful storytelling.','Rhythm and spins'],
 ['Bharatanatyam','Tamil Nadu','Strong posture, adavus, mudras and expressive abhinaya.','Discipline and culture'],
 ['Ballet','Europe','Posture, balance, grace, lines and technical foundation.','Grace and control'],
 ['Salsa','Latin culture','Social rhythm, footwork, partner awareness and musical joy.','Rhythm and fitness'],
 ['Jazz','USA','Sharp lines, kicks, turns and energetic stage expression.','Stage performance'],
 ['Contemporary','Modern dance','Flow, emotion, floor work, balance and release.','Expression and mobility'],
 ['Freestyle','Global','Personal movement, creativity, musicality and confidence.','Creative freedom'],
 ['Folk Dance','Worldwide','Community steps, cultural rhythm, formations and celebration.','Culture and teamwork']
];

let selectedAge='kids'; let selectedStyle='bollywood';
const ageMenu=document.getElementById('ageStyleMenu'); const ageContent=document.getElementById('ageContent');
function renderMenu(){ const styles=danceData[selectedAge].styles; ageMenu.innerHTML=Object.entries(styles).map(([key,s])=>`<button class="style-btn ${key===selectedStyle?'active':''}" data-style="${key}">${s.icon} ${s.name}</button>`).join(''); document.querySelectorAll('.style-btn').forEach(btn=>btn.addEventListener('click',()=>{selectedStyle=btn.dataset.style;renderMenu();renderContent();}));}
function renderContent(){ const s=danceData[selectedAge].styles[selectedStyle]; ageContent.innerHTML=`<h3>${s.icon} ${s.name} for ${danceData[selectedAge].label.split(' ')[0]}</h3><div class="chips">${s.chips.map(c=>`<span class="chip">${c}</span>`).join('')}</div><div class="quote-box">${s.quote}</div><p>${s.text}</p><p><strong>Origin:</strong> ${s.origin}. <strong>Why it works:</strong> ${s.why}</p><div class="skill-grid">${s.skills.map(k=>`<div><strong>${k}</strong><br><span>Core skill</span></div>`).join('')}</div><div class="lesson-grid">${s.lessons.map((l,i)=>`<div><h4>Lesson ${i+1}</h4><p>${l}</p></div>`).join('')}</div>`;}
document.querySelectorAll('.age-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.age-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');selectedAge=tab.dataset.age;selectedStyle=Object.keys(danceData[selectedAge].styles)[0];renderMenu();renderContent();}));
renderMenu(); renderContent();

document.getElementById('styleGrid').innerHTML=styleMeta.map(([name,origin,text,tag])=>`<article class="style-card"><h3>${name}</h3><p>${text}</p><div class="tag-row"><span>${origin}</span><span>${tag}</span></div></article>`).join('');

document.querySelector('.menu-toggle').addEventListener('click',()=>document.querySelector('.nav-links').classList.toggle('open'));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
